version: "3.8"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: wallfit_user
      POSTGRES_PASSWORD: wallfit_pass
      POSTGRES_DB: wallfit_db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./infra/initdb:/docker-entrypoint-initdb.d # scripts d'initialisation (optionnel)
    ports:
      - "5432:5432"

volumes:
  db_data:
